server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.217.128
    username: leyou
    password: 123456
    virtual-host: /leyou

leyou:
  sms:
    accessKeyId: LTAI5t8ewGhcwGua6pm4N6hE # 你自己的accessKeyId
    accessKeySecret: Kn9lyvu1wedeVl6xkrtW8OK6Vvx98K # 你自己的AccessKeySecret
    signName: 乐优平台 # 签名名称
    verifyCodeTemplate: HYW_133976814 # 模板名称