server:
  port: 8085
spring:
  application:
    name: user-service
  rabbitmq:
    host: 192.168.217.128
    username: leyou
    password: 123456
    virtual-host: /leyou
  redis:
    host: 192.168.217.128
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/leyou
    username: root
    password: 15874473705hyw
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
mybatis:
  type-aliases-package: com.leyou.user.pojo